### ISSUE TITLE
Make a new free tresure that refreshes every day

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#775] opened 2021-01-27 08:04 UTC
The idea applies to Overthrow and 12v12 too.

┆Issue is synchronized with this [Trello card](https://trello.com/c/fFLeCcjG) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment] 2021-01-27 15:24
Duplicate of https://github.com/dota2unofficial/custom_hero_clash_issues/issues/776

**Closed by fcalife** 2021-01-27 15:24 UTC
Labels: enhancement, suggestion
