### ISSUE TITLE
Bring back Juxtapose and Elder Dragon Form

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#502] opened 2020-11-19 10:20 UTC

**Comment by AustraliaIsMyCity** [comment] 2020-12-22 11:44
merged into https://github.com/dota2unofficial/custom_hero_clash_issues/issues/391

**Comment by AustraliaIsMyCity** [comment] 2021-01-05 00:09
this is a duplicate of https://github.com/dota2unofficial/custom_hero_clash_issues/issues/391

**Closed by AustraliaIsMyCity** 2021-01-05 00:09 UTC
Labels: balance, bug
