### ISSUE TITLE
I got 10th place when 3 people are disconnected and I am still alive ??

### ISSUE THREAD

**Issue by AbdoNashaat** [dota2unofficial/custom_hero_clash_issues#814] opened 2021-01-30 17:40 UTC
https://user-images.githubusercontent.com/69817574/106363696-c9cb7180-6332-11eb-9ddd-f9b88f7a1f53.png

**Comment by Draze22** [comment] 2021-02-01 04:50
Duplicate of Issue #756.

**Closed by Draze22** 2021-02-01 04:50 UTC
Labels: bug, duplicate
