### ISSUE TITLE
Fire Spirits Aghanim Shard Bug

### ISSUE THREAD

**Issue by otakuivan86** [dota2unofficial/custom_hero_clash_issues#734] opened 2021-01-14 07:42 UTC
I played game and bought Aghanim Shard. I wanted to change my skill and got fire spirits on discard. But because of behaviour of Shard, I couldn't change that skill
Please fix this bug

**Comment by Snoresville** [comment] 2021-01-14 08:14
duplicate of https://github.com/dota2unofficial/custom_hero_clash_issues/issues/671

**Closed by Snoresville** 2021-01-14 08:14 UTC
