### ISSUE TITLE
Wraith King's Vampiric Spirit does not work if learned at the fountain

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#751] opened 2021-01-22 06:17 UTC
It works fine if learned during a round, pvp, etc. Likely related to the ability being disabled as soon as its learned by the fountain regen modifier.

┆Issue is synchronized with this [Trello card](https://trello.com/c/BBDjFHG0) by [Unito](https://www.unito.io/learn-more)

**Comment by 56kyle** [comment] 2021-02-02 21:49
fixed in commit https://github.com/dota2unofficial/custom_hero_clash/commit/0fca116804ea320cee815f154ef245072d488669
can confirm fountain regen modifier was the cause

**Closed by 56kyle** 2021-02-02 21:49 UTC
Labels: bug, reproducible
