### ISSUE TITLE
Tempest Double and Bear Bug

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#523] opened 2020-11-23 22:41 UTC
![image](https://user-images.githubusercontent.com/16277198/100023326-e336d580-2e38-11eb-8441-ac639efe3c58.png)
![image](https://user-images.githubusercontent.com/16277198/100023316-df0ab800-2e38-11eb-837a-3f5143c652dd.png)

**Comment by darklordabc** [comment] 2020-11-23 22:44
A possible solution is to remove the bear ability from tempest doubles.

**Comment by Draze22** [comment] 2020-11-24 01:37
Based on bug reports this has to do with spirit bear dying in a duel and being summoned again after the duel. Base on the image below tempest double isn't required for this bug to occur.
![image](https://user-images.githubusercontent.com/63279022/100035221-c78bf900-2e51-11eb-9d28-186612458921.png)

**Comment by Draze22** [comment] 2020-11-24 01:45
Although based on this it can be caused by simply summoning spirit bear during creep rounds.
![image](https://user-images.githubusercontent.com/63279022/100035645-cb6c4b00-2e52-11eb-8d5f-43b28a5e5e48.png)

**Comment by fcalife** [comment] 2020-12-09 07:10
Duplicate of #550

**Closed by fcalife** 2020-12-09 07:10 UTC
Labels: November Fixup, bug, unknown cause
