### ISSUE TITLE
Player's who first connect to the game (after hero pick screen) while in a duel get teleported to their arena and full healed

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#480] opened 2020-11-14 09:12 UTC
This makes it very likely that they will win the duel.

**Comment by AustraliaIsMyCity** [comment] 2020-12-22 11:35
this is a duplicate of https://github.com/dota2unofficial/custom_hero_clash_issues/issues/335

**Closed by AustraliaIsMyCity** 2020-12-22 11:35 UTC
Labels: November Fixup, bug, duplicate, niche
